export const CANONICAL_COMMAND_IDS = [
    'avatar',
    'ban',
    'birthday',
    'boost',
    'cases',
    'clear',
    'config',
    'dashboard',
    'info',
    'kick',
    'leaderboard',
    'lock',
    'move',
    'moveall',
    'moveme',
    'mute',
    'ping',
    'profile',
    'rank',
    'reactionrole',
    'role',
    'roles',
    'server',
    'setlevel',
    'setnick',
    'setup',
    'setxp',
    'slowmode',
    'timeout',
    'top',
    'unban',
    'unlock',
    'unmute',
    'untimeout',
    'user',
    'verify',
    'vkick',
    'warn',
    'welcome',
] as const;

export const CANONICAL_COMMAND_ID_SET = new Set<string>(CANONICAL_COMMAND_IDS);
