// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/dashboard/[guildId]/aliases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/aliases">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/aliases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/analytics">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/birthdays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/birthdays">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/birthdays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/boosts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/boosts">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/boosts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/commands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/commands">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/commands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/docs">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/events">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/leveling/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/leveling">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/leveling/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/logs">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/moderation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/moderation">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/moderation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/polls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/polls">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/polls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/reaction-roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/reaction-roles">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/reaction-roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/role-actions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/role-actions">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/role-actions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/settings">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/verification">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/webhooks">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[guildId]/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[guildId]/welcome">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/commands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/commands">> = Specific
  const handler = {} as typeof import("../../../app/docs/commands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/dev/commands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/dev/commands">> = Specific
  const handler = {} as typeof import("../../../app/docs/dev/commands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/dev/modules/[module]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/dev/modules/[module]">> = Specific
  const handler = {} as typeof import("../../../app/docs/dev/modules/[module]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/dev/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/dev/modules">> = Specific
  const handler = {} as typeof import("../../../app/docs/dev/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/dev">> = Specific
  const handler = {} as typeof import("../../../app/docs/dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/dev/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/dev/setup">> = Specific
  const handler = {} as typeof import("../../../app/docs/dev/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/modules/[module]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/modules/[module]">> = Specific
  const handler = {} as typeof import("../../../app/docs/modules/[module]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/modules">> = Specific
  const handler = {} as typeof import("../../../app/docs/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/setup">> = Specific
  const handler = {} as typeof import("../../../app/docs/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guilds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guilds">> = Specific
  const handler = {} as typeof import("../../../app/guilds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/calendar/[userId]/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/[userId]/[token]">> = Specific
  const handler = {} as typeof import("../../../app/api/calendar/[userId]/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug/env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/env">> = Specific
  const handler = {} as typeof import("../../../app/api/debug/env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/aliases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/aliases">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/aliases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/analytics">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/api-keys/[keyId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/api-keys/[keyId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/api-keys/[keyId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/api-keys">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/birthdays/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/birthdays/config">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/birthdays/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/birthdays/entries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/birthdays/entries">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/birthdays/entries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/boosts/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/boosts/config">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/boosts/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/boosts/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/boosts/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/boosts/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/calendar-integrations/[integrationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/calendar-integrations/[integrationId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/calendar-integrations/[integrationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/calendar-integrations/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/calendar-integrations/callback">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/calendar-integrations/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/calendar-integrations/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/calendar-integrations/connect">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/calendar-integrations/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/calendar-integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/calendar-integrations">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/calendar-integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/channels">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/commands/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/commands/config">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/commands/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/discord-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/discord-data">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/discord-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/events/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/events/[eventId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/events/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/events">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/events/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/events/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/events/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/events/templates/[templateId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/events/templates/[templateId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/events/templates/[templateId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/events/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/events/templates">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/events/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/leveling/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/leveling/config">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/leveling/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/leveling/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/leveling/leaderboard">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/leveling/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/leveling/rewards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/leveling/rewards">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/leveling/rewards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/logs">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/members">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/moderation/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/moderation/config">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/moderation/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/notifications/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/notifications/preferences">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/notifications/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/notifications/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/notifications/read">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/notifications/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/notifications">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/notifications/unread-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/notifications/unread-count">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/notifications/unread-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/polls/[pollId]/results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/polls/[pollId]/results">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/polls/[pollId]/results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/polls/[pollId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/polls/[pollId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/polls/[pollId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/polls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/polls">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/polls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/polls/templates/[templateId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/polls/templates/[templateId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/polls/templates/[templateId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/polls/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/polls/templates">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/polls/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/reaction-roles/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/reaction-roles/messages">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/reaction-roles/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/reaction-roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/reaction-roles">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/reaction-roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/role-actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/role-actions">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/role-actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/settings/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/settings/export">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/settings/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/settings/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/settings/import">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/settings/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/config">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/kicked/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/kicked">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/kicked/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/role-messages/[messageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/role-messages/[messageId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/role-messages/[messageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/role-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/role-messages">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/role-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/rules/[ruleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/rules/[ruleId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/rules/[ruleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/rules">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/verification/unverified/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/verification/unverified">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/verification/unverified/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/webhooks/[webhookId]/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/webhooks/[webhookId]/logs">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/webhooks/[webhookId]/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/webhooks/[webhookId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/webhooks/[webhookId]">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/webhooks/[webhookId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/webhooks/[webhookId]/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/webhooks/[webhookId]/test">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/webhooks/[webhookId]/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/webhooks">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/welcome/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/welcome/config">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/welcome/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/welcome/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/welcome/preview">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/welcome/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/welcome/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/welcome/templates">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/welcome/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/[guildId]/welcome/triggers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds/[guildId]/welcome/triggers">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/[guildId]/welcome/triggers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/guilds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds">> = Specific
  const handler = {} as typeof import("../../../app/api/guilds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/search/telemetry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search/telemetry">> = Specific
  const handler = {} as typeof import("../../../app/api/search/telemetry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/version">> = Specific
  const handler = {} as typeof import("../../../app/api/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/dashboard/[guildId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/[guildId]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[guildId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/dev/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/docs/dev">> = Specific
  const handler = {} as typeof import("../../../app/docs/dev/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../app/docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
